db: 
  vector_db:
    type: "qdrant"
    qdrant:
      host: "localhost"
      port: 6333

      collection_name: "telegram_messages"
      
      # Distance metric to use for vector similarity search
      distance: "Cosine"

      # TODO: Specify shard key and replication factor for production deployment BELOW 
      # shard_key:
      # replication_factor:
      
      # Embedding model to use for generating vector representations of the text data 
      embedding_model: "all-MiniLM-L6-v2"
      
      # Chunk parameters for text splitting before embedding
      chunk_size: 500
      chunk_overlap: 50